package ui;

import Business.DTO.playerDTO;
import Sev.Service.playService;
import Sev.Serviceipm.playServiceImp;
import entity.player;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    playService sev;
    List<playerDTO> listStaff;
    List<player> listStaff2;
    playServiceImp serviceImp;
    public static player userLogIn;

    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        serviceImp = new playServiceImp();
        sev = new playService();
        listStaff = sev.getAll();
        listStaff2 = serviceImp.selectALL();
        userLogIn = new player();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btn_huy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_dangnhap1 = new javax.swing.JButton();
        lblQMK = new javax.swing.JLabel();
        chkShow = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ĐĂNG NHẬP");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Đăng nhập");

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btn_huy.setBackground(new java.awt.Color(255, 255, 51));
        btn_huy.setText("Hủy");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Email:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu:");

        btn_dangnhap1.setBackground(new java.awt.Color(255, 255, 51));
        btn_dangnhap1.setText("Đăng nhập");
        btn_dangnhap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhap1ActionPerformed(evt);
            }
        });

        lblQMK.setText("Quên mật khẩu?");
        lblQMK.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblQMKMouseMoved(evt);
            }
        });
        lblQMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblQMKMousePressed(evt);
            }
        });

        chkShow.setText("Hiện mật khẩu");
        chkShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(98, 98, 98))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btn_dangnhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblQMK))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkShow)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chkShow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dangnhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblQMK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed


    }//GEN-LAST:event_btn_huyActionPerformed

    private void btn_dangnhap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhap1ActionPerformed
        txtEmail.setBackground(Color.white);
        txtPass.setBackground(Color.white);
        if (txtEmail.getText().trim().length() > 0) {
            if (txtPass.getPassword().length > 0) {
                login();
            } else {
                txtPass.setBackground(Color.pink);
                JOptionPane.showMessageDialog(this, "Mật khẩu không đúng");
            }
        } else {
            txtEmail.setBackground(Color.pink);
            JOptionPane.showMessageDialog(this, "Bạn không được để trống tài khoản?");
        }
    }//GEN-LAST:event_btn_dangnhap1ActionPerformed

    private void lblQMKMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQMKMouseMoved

    }//GEN-LAST:event_lblQMKMouseMoved

    private void lblQMKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQMKMousePressed

    }//GEN-LAST:event_lblQMKMousePressed

    private void chkShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowActionPerformed

    }//GEN-LAST:event_chkShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangnhap1;
    private javax.swing.JButton btn_huy;
    private javax.swing.JCheckBox chkShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblQMK;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables

    private void login() {
//        String taiKhoan = txtEmail.getText();
//        String passw = new String(txtPass.getPassword());
//        boolean a = isValidLogin(taiKhoan, passw, listStaff2);
//        if (a = true) {
//            JOptionPane.showMessageDialog(this, "Bạn đăng nhập thành công vai trò admin");
//            PlayerUI home = new PlayerUI();
//            home.setVisible(true);
//
//        } else {
//            JOptionPane.showMessageDialog(this, "Đăng nhập thất bại");
//            abcUI h = new abcUI();
//            h.setVisible(true);
//        }
 
        String taiKhoan = txtEmail.getText();
        String passw = new String(txtPass.getPassword());
        
        
        for(int i =0; i<listStaff2.size()+1; i++){
            if(i<listStaff2.size()){
                if(listStaff2.get(i).getEmail().equals(taiKhoan) &&
                   listStaff2.get(i).getPassword().equals(passw) &&listStaff2.get(i).isRole()==true ){
                    userLogIn.setIdPlayer(listStaff2.get(i).getIdPlayer());
                    userLogIn.setPlayername(listStaff2.get(i).getPlayername());
                    userLogIn.setRole(true);
               JOptionPane.showMessageDialog(this, "Bạn đăng nhập thành công vai trò admin");
              this.dispose();
                 Home home = new Home();
                 home.setVisible(true);
                 return;
                }
                
                if(listStaff2.get(i).getEmail().equals(taiKhoan) &&
                   listStaff2.get(i).getPassword().equals(passw) &&listStaff2.get(i).isRole()==false ){
                    userLogIn.setIdPlayer(listStaff2.get(i).getIdPlayer());
                    userLogIn.setPlayername(listStaff2.get(i).getPlayername());
                    userLogIn.setRole(false);
              JOptionPane.showMessageDialog(this, "Bạn đăng nhập thành công vai trò nhân viên");  
            this.dispose();
              Home home = new Home();
                 home.setVisible(true);
                 return;
                }
            }else{
            JOptionPane.showMessageDialog(this, "Bạn đăng nhập thất bại");
            return;
            }
        }
        }
    }

//    private boolean isValidLogin(String email, String password, List<player> userList) {
//        for (player user : userList) {
//            if (user.getEmail().equals(email) && user.getPassword().equals(password)) {
//                return true;
//            }
//        }
//        return false;
//    }
//}
